server:
  port: ${SERVER_PORT:8082}

grpc:
  server:
    port: ${GRPC_SERVER_PORT:9090}

spring:
  application:
    name: auth-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/auth_db}
    username: ${SPRING_DATASOURCE_USERNAME:auth_user}
    password: ${SPRING_DATASOURCE_PASSWORD:auth_pass}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
  mail:
    host: ${SPRING_MAIL_HOST:smtp.gmail.com}
    port: ${SPRING_MAIL_PORT:587}
    username: ${SPRING_MAIL_USERNAME:}
    password: ${SPRING_MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  autocofingure:
    exclude: 
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration, 
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

app:
  grpc:
    auth:
      service-secret: ${APP_GRPC_AUTH_SERVICE_SECRET:change-me-shared-secret}
  kafka:
    topics:
      user-registered: ${APP_KAFKA_TOPIC_USER_REGISTERED:user.registered.v1}
  jwt:
    issuer: ${APP_JWT_ISSUER:ai-learning-platform-auth}
    audience: ${APP_JWT_AUDIENCE:ai-learning-platform-clients}
    access-token-expiration-minutes: ${APP_JWT_ACCESS_EXP_MINUTES:15}
    refresh-token-expiration-days: ${APP_JWT_REFRESH_EXP_DAYS:7}
    private-key-location: classpath:keys/private_key.pem
    public-key-location: classpath:keys/public_key.pem
  mail:
    from: ${APP_MAIL_FROM:no-reply@aiplatform.local}
    enabled: ${APP_MAIL_ENABLED:false}
    app-name: ${APP_MAIL_APP_NAME:AI Learning Platform}
    verify-base-url: ${APP_MAIL_VERIFY_BASE_URL:http://localhost:3000/verify-email?token=}
    reset-password-base-url: ${APP_MAIL_RESET_PASSWORD_BASE_URL:http://localhost:3000/reset-password?token=}
