services:
  postgres:
    image: postgres:15
    container_name: auth-postgres
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_pass
    ports:
      - "5432:5432"
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U auth_user -d auth_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  auth-service:
    build:
      context: ..
      dockerfile: auth-service/Dockerfile
    container_name: auth-service
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/auth_db
      SPRING_DATASOURCE_USERNAME: auth_user
      SPRING_DATASOURCE_PASSWORD: auth_pass
      GRPC_SERVER_PORT: 9090
      APP_GRPC_AUTH_SERVICE_SECRET: change-me-shared-secret
      APP_MAIL_ENABLED: "false"

  redis:
    image: redis:7-alpine
    container_name: auth-redis
    ports:
      - "6379:6379"

  api-gateway:
    build:
      context: ..
      dockerfile: api-gateway/Dockerfile
    container_name: api-gateway
    depends_on:
      - auth-service
      - redis
    environment:
      SERVER_PORT: 8080
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      GRPC_AUTH_ADDRESS: static://auth-service:9090
      APP_GRPC_AUTH_SERVICE_SECRET: change-me-shared-secret
    ports:
      - "8080:8080"

volumes:
  auth_postgres_data: